code --install-extension eamodio.gitlens
code --install-extension GitHub.copilot
code --install-extension GitHub.copilot-chat
code --install-extension golang.go
code --install-extension llvm-vs-code-extensions.vscode-clangd
code --install-extension MathWorks.language-matlab
code --install-extension maximetinu.identical-sublime-monokai-csharp-theme-colorizer
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.autopep8
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-server
code --install-extension ms-vscode.sublime-keybindings
code --install-extension SAPOS.yeoman-ui
code --install-extension SAPOSS.app-studio-remote-access
code --install-extension SAPOSS.app-studio-toolkit
code --install-extension smulyono.reveal
code --install-extension stkb.rewrap
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension twxs.cmake
code --install-extension yurihs.sublime-vscode-theme
code --install-extension ZixuanWang.linkerscript
